version: '3.8'

services:
  backend:
    build: ..
    container_name: spring-sungbok-back-blue
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8111:8080"
    networks:
      - servernetwork

networks:
  servernetwork:
    external: true
    driver: bridge